export const categories = [
  {
    id: 1,
    title: "Pizza",
    image: require("../../assets/categories/icons8-pizza-96.png"),
  },
  {
    id: 2,
    title: "Burgers",
    image: require("../../assets/categories/icons8-hamburger-96.png"),
  },
  {
    id: 3,
    title: "Cupcake",
    image: require("../../assets/categories/icons8-cupcake-emoji-96.png"),
  },
  {
    id: 4,
    title: "Noodles",
    image: require("../../assets/categories/icons8-spaghetti-96.png"),
  },
  {
    id: 5,
    title: "Fish",
    image: require("../../assets/categories/icons8-tropical-fish-96.png"),
  },
  {
    id: 6,
    title: "Drinks",
    image: require("../../assets/categories/icons8-tropical-drink-96.png"),
  },
];
// export const featured = {
//   id: 1,
//   title: "Hot and Spicy",
//   description: "soft and tender fried chicken",
//   restaurant: [
//     {
//       id: 1,
//       name: "Papa Jhons",
//       image: require("../../assets/restaurants/n7yx-hero (1).jpg"),
//       description: "Hot and Spicy Pizza",
//       lng: 77.5946,
//       lat: 12.9716,
//       address: "Kormangala, Bangalore",
//       stars: 4.5,
//       reviews: "4.4k",
//       category: "Fast Food",
//       dishes: [
//         {
//           id: 1,
//           name: "Chicken Burger",
//           description: "Chicken patty with lettuce, tomato, and cheese",
//           price: 5.99,
//           image: require("../../assets/dishes/images (1) (1).jpeg"),
//         },
//         {
//           id: 2,
//           name: "Chicken Pizza",
//           description: "Chicken pizza with cheese and veggies",
//           price: 8.99,
//           image: require("../../assets/dishes/images (2).jpeg"),
//         },
//         {
//           id: 3,
//           name: "Chicken Wings",
//           description: "Fried chicken",
//           price: 6.99,
//           image: require("../../assets/dishes/images (3).jpeg"),
//         },
//       ],
//     },
//     {
//       id: 2,
//       name: "AlBaik",
//       image: require("../../assets/restaurants/download (7).jpeg"),
//       description: "American, Fast Food",
//       lng: 77.5946,
//       lat: 12.9716,
//       address: "Kormangala, Bangalore",
//       stars: 4.5,
//       reviews: "4.4k",
//       category: "Fast Food",
//       dishes: [
//         {
//           id: 1,
//           name: "Chicken Burger",
//           description: "Chicken patty with lettuce, tomato, and cheese",
//           price: 5.99,
//           image: require("../../assets/dishes/images (1) (1).jpeg"),
//         },
//         {
//           id: 2,
//           name: "Chicken Pizza",
//           description: "Chicken pizza with cheese and veggies",
//           price: 8.99,
//           image: require("../../assets/dishes/images (2).jpeg"),
//         },
//         {
//           id: 3,
//           name: "Chicken Wings",
//           description: "Fried chicken",
//           price: 6.99,
//           image: require("../../assets/dishes/images (3).jpeg"),
//         },
//       ],
//     },
//     {
//       id: 3,
//       name: "KFC",
//       image: require("../../assets/restaurants/bdcd233971b7c81bf77e1fa4471280eb (1).webp"),
//       description: "American, Fast Food",
//       lng: 77.5946,
//       lat: 12.9716,
//       address: "Kormangala, Bangalore",
//       starts: 4.5,
//       reviews: "4.4k",
//       category: "Fast Food",
//       dishes: [
//         {
//           id: 1,
//           name: "Chicken Burger",
//           description: "Chicken patty with lettuce, tomato, and cheese",
//           price: 5.99,
//           image: require("../../assets/dishes/images (1) (1).jpeg"),
//         },
//         {
//           id: 2,
//           name: "Chicken Pizza",
//           description: "Chicken pizza with cheese and veggies",
//           price: 8.99,
//           image: require("../../assets/dishes/images (2).jpeg"),
//         },
//         {
//           id: 3,
//           name: "Chicken Wings",
//           description: "Fried chicken",
//           price: 6.99,
//           image: require("../../assets/dishes/images (3).jpeg"),
//         },
//       ],
//     },
//   ],
// };
